apiVersion: v1
kind: Secret
metadata:
  name: course-secrets
  namespace: course-management
type: Opaque
stringData:
  # Postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: root
  POSTGRES_DB: course_db
  
  # Keycloak
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  
  # Backend DB Connection (redundant but useful for clarity if needed separately)
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: root
